### ISSUE TITLE
Encountered error while reading configuration from yaml

### ISSUE THREAD

**Issue by hwdef** [longportapp/openapi-go#52]
go code
```go
	conf, err := config.New(config.WithFilePath("./config.yaml"))
	if err != nil {
		panic(err)
	}
```

yaml config
```yaml
LONGPORT_APP_KEY: "xxxxxx"
LONGPORT_APP_SECRET: "xxxxxxx"
LONGPORT_ACCESS_TOKEN: "xxxxxxxx"
```

errors:
```
panic: unsupported flag "LONGPORT_HTTP_URL" in tag "LONGBRIDGE_HTTP_URL,LONGPORT_HTTP_URL" of type config.Config [recovered]
        panic: unsupported flag "LONGPORT_HTTP_URL" in tag "LONGBRIDGE_HTTP_URL,LONGPORT_HTTP_URL" of type config.Config
```
